name: caldav_client
description: A CalDAV client for dart. It allows to make CalDAV
  requests to a server easily and quickly.
version: 1.1.0
repository: https://github.com/julisanchez/caldav_client
issue_tracker: https://github.com/julisanchez/caldav_client/issues

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  xml: ^6.5.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk:
      flutter
  mock_web_server: ^5.0.0-nullsafety.1
